; PlatformIO project for XIAO Vision AI Camera (ESP32-C3 + Grove Vision AI V2)
[env:seeed_xiao_esp32c3]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
monitor_speed = 115200
lib_deps =
  https://github.com/Seeed-Studio/Seeed_Arduino_SSCMA.git
build_flags =
  -DCORE_DEBUG_LEVEL=1
