; EE04 (XIAO ESP32-S3) + 5.83" 648x480 mono ePaper hardware demo
[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
lib_deps =
  https://github.com/Seeed-Studio/Seeed_GFX.git
build_flags =
  -DCORE_DEBUG_LEVEL=1
  -I include
monitor_filters = esp32_exception_decoder
